### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by DavidSegura182** [Vickymsg/mercado_liebre#3]
1. CUMPLE: Cuenta con los elementos requeridos del Header, Main y Footer.
 2. CUMPLE: Los íconos no cuentan con un tamaño de 2em
 3. CUMPLE: La página se adapta a diferentes resoluciones.
 4. CUMPLE: La página cuenta con un formulario de registro.
 5. CUMPLE: La página cuenta con un formulario de login.
 6. NO CUMPLE: No se muestra un mensaje de error al llenar mal el formulario de algún campo.
 7. CUMPLE: El Search Bar corresponde a un formulario.
 8. CUMPLE: Se cuenta con transiciones y animaciones de CSS.
 9. Animaciones muy bien ejecutadas en especial la animación del camión
 10. Tamaños de la fuente, debido a que en ordenador se ve un poco pequeñas las letras se podría mejorar esa parte para que se vea más legible

**Comment by Vickymsg** [comment]
Se agregaron mensajes de error en los formularios y se aumento tamaño de letra de los formularios
