### ISSUE TITLE
Peer Review- MercadoLiebre

### ISSUE THREAD

**Issue by sorrego98** [Vickymsg/mercado_liebre#4]
- [x] 1.  **CUMPLE**: Cuenta con los elementos requieridos del _Header, Main y Footer_.
- [x] 2. **NO CUMPLE**: Los íconos no cuentan con un tamaño de _2em_
- [x] 3. **CUMPLE**: La página se adapta a diferentes resoluciones.
- [x] 4. **CUMPLE**: La página cuenta con un formulario de registro.
- [x] 5. **CUMPLE**: La página cuenta con un formulario de login.
- [x] 6. **NO CUMPLE**: No se muestra un mensaje de error al llenar mal el formulario de algún campo.
- [x] 7. **CUMPLE**: El _Search Bar_ corresponde a un formulario.
- [x] 8. **CUMPLE**: Se cuenta con transiciones y animaciones de _CSS_.
- [x] 9. Me gustó el sitio en general, el formulario de _Registro_ y en especial la animación del camión.
- [x] 10.  Solo organizar los puntos que no cumple.

**Comment by Vickymsg** [comment]
Se agregaron mensajes de validacion para los campos del formulario
Los iconos del footer miden 2em
